version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERUSER
          password: $DOCKERPASS
    steps:
      - tailscale/install
      - tailscale/connect:
          ts-auth-key: TAILNET_LATEST
          ts-dst-host: 100.88.29.63
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKERUSER/project-information-retrieval:$TAG .
          docker build -t $DOCKERUSER/project-information-retrieval:latest .
          echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
          docker push $DOCKERUSER/project-information-retrieval:$TAG
          docker push $DOCKERUSER/project-information-retrieval:latest
      - run: sudo tailscale ssh $USER@$TAILNET_IP -p $TAILNET_PORT "./my-tracker/deploy.sh"
      - tailscale/disconnect

# Orchestrate our job run sequence
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main